version: "2"

services:
  api:
    container_name: api
    build: .
    ports:
      - 8076:8076
    depends_on:
      - mongodb
    links:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - 27017:27017